name = "gasko-api"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 8,14,20 * * *"]

[[kv_namespaces]]
binding = "STATIONS_CACHE"
id = "39aff7f8295f42dc9a3ce0747d9d4c5b"

[[d1_databases]]
binding = "DB"
database_name = "gasko-db"
database_id = "eb0a2750-6588-420e-b16b-6508d5930df4"

[vars]
ENV = "production"